server:
  port: 8082
  servlet:
    context-path: /

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/api"
    username: root
    password: 16092004
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false